version: '3'

volumes:
  db-volume:

services:
  app:
    container_name: zakkuri-cake-app
    build:
      context: ../
      dockerfile: ./.runtime/app/Dockerfile
    volumes:
      - ../:/opt/project:cached
      - ./app/shared_files/mount/usr/local/etc/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:cached
      - ./app/shared_files/mount/var/log/xdebug:/var/log/xdebug
    working_dir: /opt/project/app
    environment:
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
      COMPOSER_HOME: "/opt/project/app/vendor/.composer_home"
      DATABASE_URL: mysql://app_user:secret@zakkuri-cake-db/app_db
      DATABASE_TEST_URL: mysql://test_user:secret@zakkuri-cake-db/test
      PHP_IDE_CONFIG: serverName=zakkuri-cake-app
  nginx:
    image: nginx:alpine
    container_name: zakkuri-cake-nginx
    ports:
      - "8080:80"
    volumes:
      - ../app:/var/www/html
      - ./nginx/shared_files/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  db:
    image: mysql:8
    container_name: zakkuri-cake-db
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: 'rootsecret'
    ports:
      - "3341:3306"
    volumes:
      - db-volume:/var/lib/mysql:cached
      - ./database/shared_files/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d